# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'TestFramework' do
    pod 'AWSiOSSDKv2'
    pod 'AWSCognitoSync'
    pod "AFNetworking", "~> 2.0"
end

target 'TestFrameworkTests' do

end

